FROM node:12
# Create app directory
WORKDIR /usr/src/app
COPY . .
RUN adduser --disabled-password front-user
RUN usermod -a -G front-user front-user
RUN npm install
RUN npm install -g http-server
RUN npm run build
EXPOSE 80
ENTRYPOINT ["http-server", "dist/frontend/", "-p", "80", "--proxy", "http://sausage-backend:8080"]